#!/usr/bin/env bash
# scripts/clean_build_caches.sh — free disk space by removing build
# artifacts that are safe to regenerate.
#
# Default mode removes "always-safe" items only:
#   - build/Vocello.app + Vocello-macos26.dmg + release-*.log + release-metadata.txt
#     (regenerated by ./scripts/release.sh)
#   - build/audio-qc/benchmark-v2/
#     (old perf-lane recordings; not referenced by the committed
#      baseline at scripts/perf-baseline-manifest.json)
#
# --aggressive additionally wipes qa.sh + release derived-data caches
# (~11 GB extra). Next qa.sh / release.sh runs will be ~5 min slower
# while those rebuild.
#
# Always preserved (do not remove from this script):
#   - scripts/perf-baseline-manifest.json (committed; in git, not under build/)
#   - build/audio-qc/qa-perf/ (active perf-lane working dir)
#   - build/foundation/local-builds/ (current dev builds; overwritten by build_foundation_targets.sh)
#
# Use this on the 8 GB dev machine where build/ balloons to 20+ GB
# during active iteration. The repo's .gitignore already excludes
# build/, so nothing removed here is version-controlled.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
BUILD_DIR="$REPO_ROOT/build"

aggressive=false
dry_run=false

while [[ $# -gt 0 ]]; do
    case "$1" in
        --aggressive) aggressive=true; shift ;;
        --dry-run|-n) dry_run=true; shift ;;
        -h|--help)
            cat <<'EOF'
Usage: clean_build_caches.sh [--aggressive] [--dry-run|-n]

  --aggressive  Also remove qa.sh harness DerivedData + source-packages
                and foundation release derived-data (~11 GB extra).
                Next qa.sh / release.sh runs will be slower.
  --dry-run, -n Print what would be removed without removing it.
  -h, --help    Show this help.

Default removes only "always-safe" categories. See header in
scripts/clean_build_caches.sh for the full list and rationale.
EOF
            exit 0
            ;;
        *) echo "unknown arg: $1" >&2; exit 2 ;;
    esac
done

remove_path() {
    local target="$1"
    if [[ ! -e "$target" ]]; then
        return 0
    fi
    if $dry_run; then
        echo "would-remove: $target"
    else
        rm -rf "$target"
        echo "removed: $target"
    fi
}

cd "$REPO_ROOT"

echo "==> Cleaning always-safe build artifacts ..."

# Stale release build (regenerated by release.sh)
remove_path "$BUILD_DIR/Vocello.app"
remove_path "$BUILD_DIR/Vocello-macos26.dmg"
remove_path "$BUILD_DIR/release-build-settings.log"
remove_path "$BUILD_DIR/release-metadata.txt"
remove_path "$BUILD_DIR/xcodebuild-release.log"

# Old perf-lane benchmark archives. The committed baseline lives at
# scripts/perf-baseline-manifest.json; benchmark-v2 holds investigation
# recordings only.
remove_path "$BUILD_DIR/audio-qc/benchmark-v2"

if $aggressive; then
    echo "==> --aggressive: also wiping qa.sh + release derived-data ..."
    remove_path "$BUILD_DIR/harness/derived-data"
    remove_path "$BUILD_DIR/harness/source-packages"
    remove_path "$BUILD_DIR/foundation/macos-release-derived-data"
fi

echo "==> Done."
if $dry_run; then
    echo "    (dry-run; no files removed)"
fi

if [[ -d "$BUILD_DIR" ]]; then
    echo "==> build/ size after cleanup:"
    du -sh "$BUILD_DIR" 2>/dev/null || true
fi
