#!/usr/bin/env bash
# scripts/clean_build_caches.sh — free disk space by removing regenerable
# build/cache artifacts (and, opt-in, the dev model cache). Doubles as a
# disk-doctor: it always prints a reclaimable inventory first.
#
# Tiers (additive):
#   default        Always-safe items: release outputs/logs, the legacy
#                  build/Debug+build/Release split, retired-harness leftovers,
#                  and the throwaway iOS build sidecars (build/ios-uitest,
#                  build/ios-diagnostics, build/ios-diag-check, legacy build/ios-device).
#   --aggressive   Also build/DerivedData, build/foundation, the consolidated
#                  build/ios tree, and the vendored mlx-audio-swift/.build
#                  (next build is slower while those rebuild).
#   --models       Also ~/Library/Application Support/QwenVoice-Debug/models — the
#                  dev model cache (re-downloads from Hugging Face on the next
#                  debug/bench run). Usually the single biggest reclaim (~15 GB).
#   --all          == --aggressive --models
#   --dry-run, -n  Print the inventory + what would be removed; remove nothing.
#
# Always preserved by default (no flags): build/DerivedData + build/foundation +
# build/ios (incremental caches) and build/Vocello.app (the live build). The
# shipped app's ~/Library/Application Support/QwenVoice/models is reported but
# NEVER removed by this script.
#
# The repo's .gitignore excludes build/, .build/, DerivedData/ — nothing removed
# here is version-controlled. See CLAUDE.md "Storage hygiene".

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
BUILD_DIR="$REPO_ROOT/build"
VENDORED_BUILD="$REPO_ROOT/third_party_patches/mlx-audio-swift/.build"
DEBUG_MODELS="$HOME/Library/Application Support/QwenVoice-Debug/models"
SHIPPED_MODELS="$HOME/Library/Application Support/QwenVoice/models"

aggressive=false
models=false
dry_run=false

while [[ $# -gt 0 ]]; do
    case "$1" in
        --aggressive) aggressive=true; shift ;;
        --models) models=true; shift ;;
        --all) aggressive=true; models=true; shift ;;
        --dry-run|-n) dry_run=true; shift ;;
        -h|--help)
            cat <<'EOF'
Usage: clean_build_caches.sh [--aggressive] [--models] [--all] [--dry-run|-n]

  (default)     Remove always-safe artifacts: release outputs/logs, the legacy
                build/Debug+Release split, retired-harness leftovers, and the
                throwaway iOS sidecars (ios-uitest, ios-diagnostics,
                ios-diag-check, legacy ios-device).
  --aggressive  Also build/DerivedData, build/foundation, build/ios, and the
                vendored mlx-audio-swift/.build (slower next build).
  --models      Also ~/Library/Application Support/QwenVoice-Debug/models — the
                dev model cache (~15 GB; re-downloads on next debug/bench run).
  --all         == --aggressive --models
  --dry-run, -n Print the inventory + what would be removed; remove nothing.
  -h, --help    Show this help.

Always reported but never removed: the shipped app's QwenVoice/models.
See the header in scripts/clean_build_caches.sh and CLAUDE.md "Storage hygiene".
EOF
            exit 0
            ;;
        *) echo "unknown arg: $1" >&2; exit 2 ;;
    esac
done

# Human-readable size of an existing path (empty if absent/unreadable). Uses the
# `read` builtin to parse `du -sh` (no awk/cut dependency).
human() { local sz _r; read -r sz _r < <(du -sh "$1" 2>/dev/null) || true; printf '%s' "${sz:-}"; }

remove_path() {
    local target="$1"
    [[ -e "$target" ]] || return 0
    local size; size="$(human "$target")"
    if $dry_run; then
        printf 'would-remove: %-8s %s\n' "${size:-?}" "$target"
    else
        rm -rf "$target"
        printf 'removed:      %-8s %s\n' "${size:-?}" "$target"
    fi
}

cd "$REPO_ROOT"

# --- Inventory (report-only) ----------------------------------------------
echo "==> Reclaimable inventory:"
report() { [[ -e "$1" ]] && printf '    %-8s %s  [%s]\n' "$(human "$1")" "$1" "$2" || true; }
report "$BUILD_DIR" "build/ total"
report "$BUILD_DIR/DerivedData" "--aggressive"
report "$BUILD_DIR/ios" "--aggressive"
report "$VENDORED_BUILD" "--aggressive"
report "$DEBUG_MODELS" "--models"
report "$SHIPPED_MODELS" "report-only (never removed)"
echo

# --- always-safe ----------------------------------------------------------
echo "==> Cleaning always-safe build artifacts ..."
# Release outputs (regenerated by release.sh).
remove_path "$BUILD_DIR/Vocello-macos26.dmg"
remove_path "$BUILD_DIR/release-build-settings.log"
remove_path "$BUILD_DIR/release-metadata.txt"
remove_path "$BUILD_DIR/xcodebuild-release.log"
# Legacy dual-folder split + retired harness leftovers.
remove_path "$BUILD_DIR/Debug"
remove_path "$BUILD_DIR/Release"
remove_path "$BUILD_DIR/uitest"
remove_path "$BUILD_DIR/audio-qc"
remove_path "$BUILD_DIR/instruments-traces"
remove_path "$BUILD_DIR/ui-bench"
remove_path "$BUILD_DIR/harness"
# Throwaway iOS build sidecars (hybrid on-device test method, scripts/ios_device.sh).
remove_path "$BUILD_DIR/ios-uitest"
remove_path "$BUILD_DIR/ios-diagnostics"
remove_path "$BUILD_DIR/ios-diag-check"
remove_path "$BUILD_DIR/ios-device"

if $aggressive; then
    echo "==> --aggressive: also wiping DerivedData + foundation + build/ios + vendored .build (slower next build) ..."
    remove_path "$BUILD_DIR/DerivedData"
    remove_path "$BUILD_DIR/foundation"
    remove_path "$BUILD_DIR/ios"
    remove_path "$VENDORED_BUILD"
fi

if $models; then
    echo "==> --models: also wiping the dev model cache (re-downloads on next debug/bench run) ..."
    remove_path "$DEBUG_MODELS"
fi

echo "==> Done."
if $dry_run; then
    echo "    (dry-run; no files removed)"
fi
if [[ -e "$SHIPPED_MODELS" ]]; then
    echo "==> Note: shipped-app models KEPT ($(human "$SHIPPED_MODELS")) at: $SHIPPED_MODELS"
fi
if [[ -d "$BUILD_DIR" ]]; then
    echo "==> build/ size after cleanup:"
    du -sh "$BUILD_DIR" 2>/dev/null || true
fi
