import Foundation
import QwenVoiceCore

public typealias GenerationMode = QwenVoiceCore.GenerationMode
public typealias EngineLoadState = QwenVoiceCore.EngineLoadState
public typealias ClonePreparationPhase = QwenVoiceCore.ClonePreparationPhase
public typealias ClonePreparationState = QwenVoiceCore.ClonePreparationState
public typealias CloneReference = QwenVoiceCore.CloneReference
public typealias PreparedVoice = QwenVoiceCore.PreparedVoice
public typealias PreparedVoiceQualityWarning = QwenVoiceCore.PreparedVoiceQualityWarning
public typealias NativeTelemetryStageMark = QwenVoiceCore.NativeTelemetryStageMark
public typealias GenerationEvent = QwenVoiceCore.GenerationEvent
public typealias GenerationRequest = QwenVoiceCore.GenerationRequest
public typealias GenerationResult = QwenVoiceCore.GenerationResult
public typealias TTSEngineSnapshot = QwenVoiceCore.TTSEngineSnapshot
public typealias EngineBatchProgressUpdate = QwenVoiceCore.EngineBatchProgressUpdate
